### ISSUE TITLE
DB2 Connection Issues

### ISSUE THREAD

**Issue by kondalarao** [IBM/AI-mergency#7]
Error: Cannot initialize database: [IBM][CLI Driver] SQL30082N  Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID").  SQLSTATE=08001

    at Object.<anonymous> (F:\AI-mergency\node_app\db.js:29:9)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (F:\AI-mergency\node_app\app.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)

**Comment by kondalarao** [comment]
I just followed on what's been described on main page when we wanted to run this application locally.

**Comment by krook** [comment]
@twgoetz @alexlang74 @szerfass @jstuetzle any ideas on this DB2 issue?

**Comment by twgoetz** [comment]
Did you follow all the steps under **Creating required service instances**?
